use crate::delegation::authorization::permission::Permission;
use serde::{Deserialize, Serialize};

/// Request-specific context that a verifier uses to authorize a concrete action.
///
/// The challenge must be generated by the calling gateway/verifier and treated as one-time.
/// This structure only carries the challenge; replay tracking is intentionally left to the
/// gateway layer.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct AuthorizationRequest {
    presenter_id: String,
    audience: String,
    challenge: String,
    required_permission: Permission,
}

impl AuthorizationRequest {
    pub fn new(
        presenter_id: String,
        audience: String,
        challenge: String,
        required_permission: Permission,
    ) -> Result<Self, String> {
        if presenter_id.trim().is_empty() {
            return Err(String::from("Presenter id cannot be empty"));
        }
        if audience.trim().is_empty() {
            return Err(String::from("Authorization request audience cannot be empty"));
        }
        if challenge.trim().is_empty() {
            return Err(String::from("Authorization request challenge cannot be empty"));
        }

        Ok(Self {
            presenter_id,
            audience,
            challenge,
            required_permission,
        })
    }

    pub fn presenter_id(&self) -> &String {
        &self.presenter_id
    }

    pub fn audience(&self) -> &String {
        &self.audience
    }

    pub fn challenge(&self) -> &String {
        &self.challenge
    }

    pub fn required_permission(&self) -> &Permission {
        &self.required_permission
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::delegation::authorization::operation::Operation;

    fn permission() -> Permission {
        Permission::new(
            String::from("https://gitea.local/repos/project-a"),
            Operation::ReadFile,
        )
        .expect("test permission must be valid")
    }

    #[test]
    fn authorization_request_requires_binding_values() {
        assert!(
            AuthorizationRequest::new(
                String::new(),
                String::from("cloud-access-gateway"),
                String::from("challenge-1"),
                permission(),
            )
            .is_err()
        );

        assert!(
            AuthorizationRequest::new(
                String::from("agent-1"),
                String::new(),
                String::from("challenge-1"),
                permission(),
            )
            .is_err()
        );

        assert!(
            AuthorizationRequest::new(
                String::from("agent-1"),
                String::from("cloud-access-gateway"),
                String::new(),
                permission(),
            )
            .is_err()
        );
    }
}
