#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNTIME_DIR="$ROOT_DIR/poc/infra/runtime"
OUT_FILE="$RUNTIME_DIR/trust.env"

mkdir -p "$RUNTIME_DIR"

export RPC_URL="${RPC_URL:-http://anvil:8545}"
export CHAIN_ID="${CHAIN_ID:-31337}"
export ANVIL_DEPLOYER_PRIVATE_KEY="${ANVIL_DEPLOYER_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"

echo "Deploying local trust contracts against $RPC_URL ..."

if ! deploy_output="$(bash "$ROOT_DIR/blockchain/scripts/deploy-local.sh" 2>&1)"; then
  printf '%s\n' "$deploy_output" >&2
  echo "Trust contract deployment failed." >&2
  exit 1
fi
printf '%s\n' "$deploy_output"

extract_value() {
  local key="$1"
  printf '%s\n' "$deploy_output" | awk -F= -v key="$key" '$1 == key {value=$2} END {print value}'
}

DID_REGISTRY_ADDRESS="$(extract_value DID_REGISTRY_ADDRESS)"
ENTERPRISE_TRUST_REGISTRY_ADDRESS="$(extract_value ENTERPRISE_TRUST_REGISTRY_ADDRESS)"
ISSUER_REGISTRY_ADDRESS="$(extract_value ISSUER_REGISTRY_ADDRESS)"
GOVERNANCE_ADDRESS="$(extract_value GOVERNANCE_ADDRESS)"

for address in "$DID_REGISTRY_ADDRESS" "$ENTERPRISE_TRUST_REGISTRY_ADDRESS" "$ISSUER_REGISTRY_ADDRESS"; do
  if [[ ! "$address" =~ ^0x[0-9a-fA-F]{40}$ ]]; then
    echo "Invalid deployed contract address: $address" >&2
    exit 1
  fi
  code="$(cast code "$address" --rpc-url "$RPC_URL")"
  if [[ -z "$code" || "$code" == "0x" ]]; then
    echo "No bytecode found at deployed address $address" >&2
    exit 1
  fi
done

cat >"$OUT_FILE" <<EOF
# Generated by poc/scripts/bootstrap-trust.sh
# Public local PoC runtime values only. No private keys are written here.
RPC_URL=$RPC_URL
CHAIN_ID=$CHAIN_ID
GOVERNANCE_ADDRESS=$GOVERNANCE_ADDRESS
DID_REGISTRY_ADDRESS=$DID_REGISTRY_ADDRESS
ENTERPRISE_TRUST_REGISTRY_ADDRESS=$ENTERPRISE_TRUST_REGISTRY_ADDRESS
ISSUER_REGISTRY_ADDRESS=$ISSUER_REGISTRY_ADDRESS
EOF

echo "Trust bootstrap completed."
echo "Runtime public addresses written to $OUT_FILE"
