#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_SCRIPT="$ROOT_DIR/blockchain/scripts/deploy-local.sh"
CHECK_SCRIPT="$ROOT_DIR/blockchain/scripts/check-pre-gateway.sh"
RUNTIME_ENV_FILE="$ROOT_DIR/.git/pre-gateway-local.env"

export PATH="$HOME/.foundry/bin:$PATH"

export RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"
export CHAIN_ID="${CHAIN_ID:-31337}"

# Standard deterministic Anvil mnemonic and accounts.
# These keys are public development keys and MUST NEVER be reused outside this local PoC.
ANVIL_MNEMONIC="test test test test test test test test test test test junk"
export ANVIL_DEPLOYER_PRIVATE_KEY="${ANVIL_DEPLOYER_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
export GOVERNANCE_PRIVATE_KEY="${GOVERNANCE_PRIVATE_KEY:-$ANVIL_DEPLOYER_PRIVATE_KEY}"
export ROOT_PRIVATE_KEY="${ROOT_PRIVATE_KEY:-0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d}"
export HOLDER_PRIVATE_KEY="${HOLDER_PRIVATE_KEY:-0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a}"

for command_name in anvil forge cast cargo node npm; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "Required command not found: $command_name" >&2
    exit 1
  fi
done

if cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then
  echo "A JSON-RPC node is already responding at $RPC_URL." >&2
  echo "Stop the existing local node first so this script can start a fresh persistent Anvil chain." >&2
  exit 1
fi

echo "============================================================"
echo "Delegation thesis - persistent local pre-Gateway session"
echo "============================================================"
echo "Starting a fresh Anvil chain that will remain available after validation..."

if command -v mintty >/dev/null 2>&1 && [[ -n "${MSYSTEM:-}" ]]; then
  ANVIL_LAUNCHER="$(mktemp "${TMPDIR:-/tmp}/delegation-anvil-launcher.XXXXXX.sh")"

  cat >"$ANVIL_LAUNCHER" <<EOF
#!/usr/bin/env bash
trap 'rm -f "$ANVIL_LAUNCHER"' EXIT
export PATH="$HOME/.foundry/bin:$PATH"

echo "============================================================"
echo "Delegation thesis - Anvil"
echo "RPC: $RPC_URL"
echo "Chain ID: $CHAIN_ID"
echo "This window intentionally stays open for manual tests."
echo "Press Ctrl+C here when you want to stop Anvil."
echo "============================================================"
echo

anvil --chain-id "$CHAIN_ID" --mnemonic "$ANVIL_MNEMONIC"
EOF

  mintty -t "Delegation Anvil - chain $CHAIN_ID" /usr/bin/bash "$ANVIL_LAUNCHER" >/dev/null 2>&1 &
  echo "Opened Anvil in a separate Git Bash window."
else
  ANVIL_LOG="$ROOT_DIR/.git/pre-gateway-anvil.log"
  nohup anvil \
    --chain-id "$CHAIN_ID" \
    --mnemonic "$ANVIL_MNEMONIC" \
    >"$ANVIL_LOG" 2>&1 &
  echo "Started Anvil in the background."
  echo "Anvil log: $ANVIL_LOG"
fi

rpc_ready=false
for ((attempt = 1; attempt <= 75; attempt++)); do
  if cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then
    rpc_ready=true
    break
  fi

  sleep 0.2
done

if [[ "$rpc_ready" != "true" ]]; then
  echo "Anvil did not become ready at $RPC_URL." >&2
  echo "Check the Anvil window/log for the startup error." >&2
  exit 1
fi

observed_chain_id="$(cast chain-id --rpc-url "$RPC_URL" | tr -d '\r\n ')"
if [[ "$observed_chain_id" != "$CHAIN_ID" ]]; then
  echo "Unexpected Anvil chain id: expected $CHAIN_ID, got $observed_chain_id" >&2
  exit 1
fi

echo "Anvil ready (chainId=$observed_chain_id)."
echo
echo "Deploying local contracts..."

if ! deploy_output="$(bash "$DEPLOY_SCRIPT" 2>&1)"; then
  printf '%s\n' "$deploy_output" >&2
  echo "Local contract deployment failed. Anvil has been left running for debugging." >&2
  exit 1
fi
printf '%s\n' "$deploy_output"

extract_address() {
  local key="$1"
  local value

  value="$(
    printf '%s\n' "$deploy_output" |
      awk -F= -v key="$key" '$1 == key {value=$2} END {print value}'
  )"

  if [[ ! "$value" =~ ^0x[0-9a-fA-F]{40}$ ]]; then
    echo "Could not extract a valid $key from deploy-local.sh output." >&2
    exit 1
  fi

  printf '%s' "$value"
}

export DID_REGISTRY_ADDRESS="$(extract_address DID_REGISTRY_ADDRESS)"
export ENTERPRISE_TRUST_REGISTRY_ADDRESS="$(extract_address ENTERPRISE_TRUST_REGISTRY_ADDRESS)"
export ISSUER_REGISTRY_ADDRESS="$(extract_address ISSUER_REGISTRY_ADDRESS)"

export GOVERNANCE_ADDRESS="$(cast wallet address --private-key "$GOVERNANCE_PRIVATE_KEY")"
ROOT_ADDRESS="$(cast wallet address --private-key "$ROOT_PRIVATE_KEY")"
HOLDER_ADDRESS="$(cast wallet address --private-key "$HOLDER_PRIVATE_KEY")"
CHAIN_HEX="$(printf '0x%x' "$CHAIN_ID")"
export ROOT_ID="did:ethr:${CHAIN_HEX}:${ROOT_ADDRESS}"
export HOLDER_ID="did:ethr:${CHAIN_HEX}:${HOLDER_ADDRESS}"

write_export() {
  local name="$1"
  printf 'export %s=%q\n' "$name" "${!name}"
}

{
  echo "# Generated by blockchain/scripts/run-pre-gateway-local.sh"
  echo "# Local deterministic Anvil development values only."
  write_export RPC_URL
  write_export CHAIN_ID
  write_export ANVIL_DEPLOYER_PRIVATE_KEY
  write_export GOVERNANCE_PRIVATE_KEY
  write_export ROOT_PRIVATE_KEY
  write_export HOLDER_PRIVATE_KEY
  write_export GOVERNANCE_ADDRESS
  write_export ROOT_ID
  write_export HOLDER_ID
  write_export DID_REGISTRY_ADDRESS
  write_export ENTERPRISE_TRUST_REGISTRY_ADDRESS
  write_export ISSUER_REGISTRY_ADDRESS
} >"$RUNTIME_ENV_FILE"

echo
echo "Automatically configured deployment:"
echo "DID_REGISTRY_ADDRESS=$DID_REGISTRY_ADDRESS"
echo "ENTERPRISE_TRUST_REGISTRY_ADDRESS=$ENTERPRISE_TRUST_REGISTRY_ADDRESS"
echo "ISSUER_REGISTRY_ADDRESS=$ISSUER_REGISTRY_ADDRESS"
echo "ROOT_ID=$ROOT_ID"
echo "HOLDER_ID=$HOLDER_ID"
echo
echo "Runtime environment saved locally to:"
echo "$RUNTIME_ENV_FILE"
echo
echo "Running complete pre-Gateway validation..."

if ! bash "$CHECK_SCRIPT"; then
  echo >&2
  echo "Pre-Gateway validation failed." >&2
  echo "Anvil has intentionally been left running so you can inspect the chain." >&2
  echo "The generated environment is available at $RUNTIME_ENV_FILE" >&2
  exit 1
fi

echo
echo "============================================================"
echo "PERSISTENT PRE-GATEWAY SESSION: READY"
echo "Fresh Anvil -> deploy -> configure -> validate completed."
echo "Anvil is still running and the validated chain state is preserved."
echo "The current terminal will now become an interactive Bash with"
echo "all RPC, key, DID, and registry variables already exported."
echo
echo "Note: the validation deliberately leaves the demo credential"
echo "revoked in Status List version 2."
echo
echo "To stop the blockchain later, press Ctrl+C in the Anvil window."
echo "To leave the configured shell, type: exit"
echo "============================================================"
echo

cd "$ROOT_DIR"
exec bash -i
